name: Build and Release ccat

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Build target (server, tablet, redmi, all)'
        required: true
        default: 'all'
      version:
        description: 'Release version (e.g. v1.0.0)'
        required: true

  push:
    tags:
      - 'v*'

jobs:
  build-and-tag:
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Go
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      # Set git user to allow tagging
      - name: Configure git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      # Build all requested binaries
      - name: Build binaries
        run: |
          set -ex
          mkdir -p dist/

          build_ccat() {
            local name="$1"
            local goos="$2"
            local goarch="$3"
            local goarm="$4"

            echo "==> Building $name"
            export GOOS="$goos"
            export GOARCH="$goarch"
            export GOARM="$goarm"

            if [ "$name" = "server" ]; then
              export CGO_ENABLED=0
              export GOMIPS=softfloat
            fi

            go build -v -o "dist/ccat-$name" ./main.go
          }

          TARGET="${{ github.event.inputs.target }}"

          if [[ "$TARGET" == "server" || "$TARGET" == "all" ]]; then
            build_ccat server linux arm 5
          fi
          if [[ "$TARGET" == "tablet" || "$TARGET" == "all" ]]; then
            build_ccat tablet android arm 7
          fi
          if [[ "$TARGET" == "redmi" || "$TARGET" == "all" ]]; then
            build_ccat redmi android arm64 ""
          fi

      # Create and push git tag
      - name: Create and push tag
        run: |
          TAG="${{ github.event.inputs.version }}"
          git tag -a "$TAG" -m "Release $TAG"
          git push origin "$TAG"

      # Save built artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ccat-binaries
          path: dist/*

  release:
    runs-on: ubuntu-latest
    needs: build-and-tag
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      # Checkout again to match tag context
      - name: Checkout code
        uses: actions/checkout@v4

      # Download artifacts
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: ccat-binaries
          path: dist/

      # Create GitHub Release
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: dist/*
          name: Release ${{ github.ref_name }}
          body: |
            Released by: ${{ github.actor }}
